spring:
  datasource:
    url: jdbc:sqlserver://java-books-sql.database.windows.net:1433;database=Books-data;user=piyush@java-books-sql;password={Viking@123};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: piyush
    password: Viking@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8081